--ALTER TABLE Buyer
--ADD UserName VARCHAR(255);
--ALTER TABLE Buyer
--ADD Email VARCHAR(255);
--ALTER TABLE Buyer
--ADD About VARCHAR(255);
--ALTER TABLE Buyer
--ADD [Image] VARCHAR(255);

--DELETE FROM Buyer
--                            WHERE Id = 1
--DELETE FROM Buyer
--                            WHERE Id = 2
--DELETE FROM Buyer
--                            WHERE Id = 3
--DELETE FROM Buyer
--                            WHERE Id = 4
--
--INSERT INTO Buyer (FirebaseUserId, [Name], UserName, Email, About, [Image], [Role]) VALUES ('e63vr1XHHigSVCLoDlJs2L0HdnV2', 'Albert Chittaphong', 'albertchitta', 'albert123@gmail.com', 'Albert About Me', 'https://bootdey.com/img/Content/avatar/avatar2.png', 'Admin');
--INSERT INTO Buyer (FirebaseUserId, [Name], UserName, Email, About, [Image], [Role]) VALUES ('Y14CjkUJgiUj6R0GgUO6VkCt4tw2', 'Klay Thacker', 'KlayTT', 'klay123@gmail.com', 'Klay About Me', 'https://bootdey.com/img/Content/avatar/avatar6.png', 'Admin');
--INSERT INTO Buyer (FirebaseUserId, [Name], UserName, Email, About, [Image], [Role]) VALUES ('XlTocXr2MKQ05Emi9CpI7aIfd073', 'Gabriel Smith', 'Gabrielsmith1998', 'gabriel123@gmail.com', 'Gabriel About Me', 'https://bootdey.com/img/Content/avatar/avatar4.png', 'User');
--INSERT INTO Buyer (FirebaseUserId, [Name], UserName, Email, About, [Image], [Role]) VALUES ('AVukDXArGdfEYdDn6vbmpJ99Hbu1', 'Nathan Blackman', 'NathanBlackman', 'nathan123@gmail.com', 'Nathan About Me', 'https://bootdey.com/img/Content/avatar/avatar5.png', 'User');
