--ALTER TABLE Buyer
--ADD UserName VARCHAR(255);
--ALTER TABLE Buyer
--ADD Email VARCHAR(255);
--ALTER TABLE Buyer
--ADD About VARCHAR(255);
--ALTER TABLE Buyer
--ADD [Image] VARCHAR(255);

--DELETE FROM Buyer
--                            WHERE Id = 1
--DELETE FROM Buyer
--                            WHERE Id = 2
--DELETE FROM Buyer
--                            WHERE Id = 3
--DELETE FROM Buyer
--                            WHERE Id = 4

--INSERT INTO Buyer ([Name], UserName, Email, About, [Image]) VALUES('Albert Chittaphong', 'albertchitta', 'albert123@gmail.com', 'Albert About Me', 'https://bootdey.com/img/Content/avatar/avatar2.png');
--INSERT INTO Buyer ([Name], UserName, Email, About, [Image]) VALUES('Klay Thacker', 'KlayTT', 'klay123@gmail.com', 'Klay About Me', 'https://bootdey.com/img/Content/avatar/avatar6.png');
--INSERT INTO Buyer ([Name], UserName, Email, About, [Image]) VALUES('Gabriel Smith', 'Gabrielsmith1998', 'gabriel123@gmail.com', 'Gabriel About Me', 'https://bootdey.com/img/Content/avatar/avatar4.png');
--INSERT INTO Buyer ([Name], UserName, Email, About, [Image]) VALUES('Nathan Blackman', 'NathanBlackman', 'nathan123@gmail.com', 'Nathan About Me', 'https://bootdey.com/img/Content/avatar/avatar5.png');
--INSERT INTO Buyer ([Name], UserName, Email, About, [Image]) VALUES('test', 'NathanBlackman', 'nathan123@gmail.com', 'Nathan About Me', 'https://bootdey.com/img/Content/avatar/avatar5.png');